### ISSUE TITLE
Predictions differences

### ISSUE THREAD

**Issue by polaxgr** [STAR-Fusion/STAR-Fusion#119]
Hi. Can someone please explain to me the difference between star-fusion.fusion_candidates.preliminary(filtered - and all variations of that file ) with the star-fusion.fusion_predictions.tsv ? Thanks

**Comment by brianjohnhaas** [comment]
star-fusion.fusion_predictions.tsv

**Comment by brianjohnhaas** [comment]
Hi,

The star-fusion.fusion_predictions.tsv  contains all the fusions that passed the many filters used in star-fusion (expression, paralogs, red herrings, etc.).

The preliminary file should have all the candidates that were considered, and only a subset make them through the filters to get to the final result file.

best,

~b
