### ISSUE TITLE
Extract spanning reads supporting gene fusion

### ISSUE THREAD

**Issue by pwanj** [STAR-Fusion/STAR-Fusion#128]
Hello,
Please can you tell me how to get the spanning reads supporting a gene fusion reported by STAR-fusion. I would really appreciate it.
Thanks!

**Comment by brianjohnhaas** [comment]
Sure thing.

There's a parameter  STAR-Fusion --extract_fusion_reads

If you already ran your STAR-Fusion job, just rerun it with that option
added, and it should just pull out the evidence reads.  The reads should
get labeled according to whether they're junction vs. spanning reads, too.

best,

~brian


On Wed, May 1, 2019 at 5:02 PM Pankhuri Wanjari <notifications@github.com>
wrote:
>
> Hello,
> Please can you tell me how to get the spanning reads supporting a gene
fusion reported by STAR-fusion. I would really appreciate it.
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
