### ISSUE TITLE
Version without using igv-reports?

### ISSUE THREAD

**Issue by axelgschwind** [STAR-Fusion/STAR-Fusion#129]
Hello,

we use STAR-fusion in our somatic RNA pipeline to detect fusions in RNA tumor samples.
STAR-fusion 1.5.0 performed well. However, for v. 1.6.0 we need igv-reports. 
Unfortunately, the only way to install that package is to using pip. Since we use multiple servers, we strongly try to avoid using pip. Instead, we prefer to install python packages using apt.
Is it maybe possible to use STAR-fusion 1.6.0 without igv-reports?

Greetings,

Axel

**Comment by brianjohnhaas** [comment]
Hi,

Should be fine for star fusion but fusion inspector won't work.  Can you
use our docker image or convert to a singularity image?

-via googleFi
