### ISSUE TITLE
Star-Fusion's Aligned.out.bam usable for downstream analysis?

### ISSUE THREAD

**Issue by CPTPaso** [STAR-Fusion/STAR-Fusion#131]
Hi,

I am using Star-Fusion 1.5.0 with the Star aligner 2.6.1 to call fusion genes. I used prep_genome_lib.pl to build a reference from CTAT_HumanFusionLib.v0.1.0.dat.gz. Next, I want to analyse differential expression in my samples and I was wondering if I could directly use the Aligned.out.bam output of Star-Fusion for the generation of a read count matrix for instance with htseq-count. 

When launched, Star-Fusion runs :

`* Running CMD: /home/p/p_sosc01/miniconda2/envs/star-fusion/bin/STAR --genomeDir /home/p/p_sosc01/miniconda2/pkgs/star-fusion-1.5.0-0/hg19_star261d//ref_genome.fa.star.idx  --outReadsUnmapped None  --chimSegmentMin 12  --chimJunctionOverhangMin 12  --chimOutJunctionFormat 1  --alignSJDBoverhangMin 10  --alignMatesGapMax 100000  --alignIntronMax 100000  --alignSJstitchMismatchNmax 5 -1 5 5  --runThreadN 4 --outSAMstrandField intronMotif  --outSAMunmapped Within  --outSAMtype BAM Unsorted  --readFilesIn /scratch/tmp/e0np/CPT/cpt/input/R9_S41_R1_001.fastq /scratch/tmp/e0np/CPT/cpt/input/R9_S41_R2_001.fastq  --outSAMattrRGline ID:GRPundef  --chimMultimapScoreRange 10 --chimMultimapNmax 10 --chimNonchimScoreDropMin 10  --peOverlapNbasesMin 12 --peOverlapMMp 0.1  --genomeLoad NoSharedMemory  --twopassMode Basic`

The code used for the Star alignment in a htseq tutorial (https://bioinformatics.uconn.edu/resources-and-events/tutorials-2/rna-seq-tutorial-with-reference-genome/) differs form the one part of the Star-fusion piepline.

So, do I have to align my reads once again or can I use the .bam file generated by Star-Fusion?

Thank you very much for your help!

**Comment by brianjohnhaas** [comment]
Should be fine.  You might need to coord sort the bam file if it's not
already sorted.

-via googleFi
