### ISSUE TITLE
Error with running, i made sure i installed all the perl modules recommended

### ISSUE THREAD

**Issue by jlee110** [STAR-Fusion/STAR-Fusion#135]
perl STAR-Fusion --genome_lib_dir GRCh38_gencode_v29_CTAT_lib_Mar272019.plug-n-play/ctat_genome_lib_build_dir -J Chimeric.out.junction --output_dir data/StarFusionOut --FusionInspector validate --examine_coding_effect --denovo_reconstruct --CPU 12
-sample contains 44184777
* Running CMD: /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/util/STAR-Fusion.map_chimeric_reads_to_genes  --genome_lib_dir /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/GRCh38_gencode_v29_CTAT_lib_Mar272019.plug-n-play/ctat_genome_lib_build_dir  -J /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/Chimeric.out.junction  > /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/data/StarFusionOut/star-fusion.preliminary/star-fusion.junction_breakpts_to_genes.txt
IntervalTree.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xde00080)
Error, cmd: /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/util/STAR-Fusion.map_chimeric_reads_to_genes  --genome_lib_dir /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/GRCh38_gencode_v29_CTAT_lib_Mar272019.plug-n-play/ctat_genome_lib_build_dir  -J /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/Chimeric.out.junction  > /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/data/StarFusionOut/star-fusion.preliminary/star-fusion.junction_breakpts_to_genes.txt died with ret 256 No such file or directory at /home/jlee110/Documents/star/STAR-Fusion-v1.6.0/PerlLib/Pipeliner.pm line 181.
	Pipeliner::run(Pipeliner=HASH(0x175b808)) called at STAR-Fusion line 678

**Comment by brianjohnhaas** [comment]
It looks like the installation wasn't fully compatible with the machine the
job was run on.

Error msg was
IntervalTree.c: loadable library and perl binaries are mismatched (got
handshake key 0xdb00080, needed 0xde00080)

Try running 'make clean && make'  in the star fusion base installation
directory on the machine where it's going to run.

-via googleFi

**Comment by jlee110** [comment]
thank you, very much.
