### ISSUE TITLE
About arguments

### ISSUE THREAD

**Issue by JJMaggie** [STAR-Fusion/STAR-Fusion#142]
Hi，

we detected gene fusion by FISH experiment，but we did not detect the same gene fusion by STAR-fusion，which argument can I adjust to looson the detection conditions?

best

**Comment by brianjohnhaas** [comment]
Hi

Do you find it among the preliminary fusion results?

-via googleFi

**Comment by JJMaggie** [comment]
Hi，

Thanks for reply,  I did not find that gene fusion in "star-fusion.fusion_predictions.tsv" file.

**Comment by brianjohnhaas** [comment]
There should be a preliminary fusions file that has all possible
candidates.  It's likely in a subdirectory of the output dir

I can send more specifics later if needed.  Currently traveling

-via googleFi

**Comment by JJMaggie** [comment]
Thanks very very much，I have found the preliminary file in star-fusion.preliminary directory.

Best~
