### ISSUE TITLE
counting mates as one read versus separate reads

### ISSUE THREAD

**Issue by nairasha** [STAR-Fusion/STAR-Fusion#143]
Hi Brian,

I had two (related) questions regarding fusion supporting reads from STAR-Fusion:

1. I am processing FFPE samples and since they have short RNA fragments, I am using the STAR aligner parameter --peOverlapNbasesMin 20 so that overlapping mates can be merged into single reads to help with chimera detection. 
In such cases when STAR-Fusion reports fusion supporting reads (JunctionReads & SpanningFrags), are the numbers calculated by counting both reads in the pair separately, or are they counted just once since they are merged into a single read? I have a fusion in an FFPE sample for which Tophat-Fusion reports ~ 1000 reads and ~500 from STAR-Fusion, hence the question. Please let me know if you'd like more details.

2. I guess this question may be answered by the above, but just to confirm, for JunctionReads & SpanningFrags, does STAR-Fusion only count fusion supporting reads as fragments (R1 and R2 form one fragment) and not count singleton reads (R1 or R2) that may span the fusion junction?

Thanks much!
Asha

**Comment by brianjohnhaas** [comment]
Hi,

Only fragments are counted.  When star merges read, that'll count as a
single fragment.  When reads are paired, the two reads count as a single
frag.

Best,

-via googleFi

**Comment by nairasha** [comment]
Thanks Brian!
