### ISSUE TITLE
chimOutType Must Be Left At Default Value

### ISSUE THREAD

**Issue by DarioS** [STAR-Fusion/STAR-Fusion#150]
It might be useful for some first-time users if the wiki mentioned that `--chimOutType` shouldn't be changed from its default value. I have just mapped a RNA-seq data set with `--chimOutType WithinBAM` and I guess I'll start over again to be able to use STAR-Fusion.

**Comment by brianjohnhaas** [comment]
Right.  The wiki has the full STAR command in case you don't want star
fusion to run it automatically

-via googleFi

**Comment by DarioS** [comment]
I see the suggested STAR command in the wiki, but it's unclear which parameters are essential and which are performance tweaks and it doesn't mention the necessity to leave `--chimOutType` untouched. Users may decide to use STAR-Fusion weeks after they have completed mapping with STAR. Only two days ago, another researcher [requested the exact feature I would like to use](https://github.com/alexdobin/STAR/issues/685).

**Comment by brianjohnhaas** [comment]
wiki documentation is now updated to indicate essential parameters and those relevant to chimera detection.
