### ISSUE TITLE
Specify STAR Path and FusionInspector Parameter

### ISSUE THREAD

**Issue by DarioS** [STAR-Fusion/STAR-Fusion#151]
Some systems have multiple installations of STAR. For example,

```
$ STAR --version
STAR_2.5.3a
$ STARnew --version
2.7.1a
```

I don't think it's possible to manually specify which one to use by STAR-Fusion. Currently, I get the error "Sorry, version [STAR_2.5.3a] is not supported. Please use at least STAR version 2.7.0f". Also, the wiki suggests that `--FusionInspector inspect` is a parameter and value that could be passed to STAR-Fusion and it's value but `STAR-Fusion -h` does not list it as a possibility.

**Comment by brianjohnhaas** [comment]
Hi Dario

Theres a more extensive options list with --show full usage info

That includes FI and other options.  The wiki documentation is your best
soure for more information

-via googleFi
