### ISSUE TITLE
Missing FFPM values from STAR-Fusion 1.7 output

### ISSUE THREAD

**Issue by kmavrommatis** [STAR-Fusion/STAR-Fusion#166]
Hi, 
after upgrading from STAR-fusion 1.5 to version 1.7 I don't get any of the FFPM files anymore in the FusionInspector-validate directory.
I am using the docker image from dockerhub and the command that is used to run STAR fusion is:

```
/usr/local/src/STAR-Fusion/STAR-Fusion --output_dir . \
--verbose_level 0 \
--genome_lib_dir /data/Homo_sapiens/GRCh38/STAR-Fusion170/ \
--CPU 24 \
--denovo_reconstruct \
--examine_coding_effect \
--FusionInspector validate \
--left_fq /data/Human_R1.fastq.gz \
--right_fq /data/Human_R2.fastq.gz &&\
 rm -rf _[Ssf]*  &&\
 rm -rf FusionInspector-validate/fi_workdir  &&\
 rm -rf FusionInspector-validate/chckpts_dir &&\
 rm -rf star-fusion.preliminary
```

Has this functionality been removed?
Is there a way to compute the FFPM based on the current output?

Thanks

**Comment by brianjohnhaas** [comment]
This is resolved in the upcoming release.  In 'inspect' mode, it'll not report FFPM, but in 'validate' mode it will.  It should have worked fine in the earlier release, but it required that you had more than 100k reads as input - a hack to differentiate typical full sample modes (involving many more input reads) from test runs where FFPM values wouldn't be meaningful.  Now it better differentiates modes based on the inspect vs. validate settings.
