### ISSUE TITLE
Filtered out reads anchored in two genes

### ISSUE THREAD

**Issue by helloeoh001** [STAR-Fusion/STAR-Fusion#169]
Hello,

I have another issue about filitering reads.
A good number of fusion-candidate reads were filtered out in the file 'star-fusion.junction_breakpts_to_genes.txt.fail' becase they did not anchor in two genes.
But some of them clearly overarched two genes when aligned by BLAST.
One of the sequences filtered out, but aligned to two genes (RUNX1-EBF1) is below. 

#################################################################### 
@M70508:92:000000000-CM35J:1:1101:15591:7078
CGAGGCTTTGGCAGGCCGAGGCCAGGAGGGGCGGGAGGCTGGTGCTGACTGATGGTCCTGTCATCCCGGTTCAGGATGCCACTGCCAAACTTCATGCCAATTAGTGTATGAAGGCCAAGACAAGAACCCAGAAATGTGCCGAGTCTTGCTC
#####################################################################
<star-fusion.junction_breakpts_to_genes.txt.fail, hg38>

#only Pct (0.00%) of alignments had paired gene anchors
chr5    159084735       +       chr21   34819697        +       0       0       1       M70508:92:000000000-CM35J:1:1101:15591:7078     158840058       53M233285N69M11201N29M-9p49M102S        34819698        49S102M 1       302     201     296     296     0       GRPundef        [{"delta":5,"sense_or_antisense":"antisense","pt_exon":"159084739","pt_align":159084734,"gene_id":"EBF1^ENSG00000164330.17","anchor_length":49,"exon":{"rend":"159084739","token":"EBF1^ENSG00000164330.17^159084666^159084739^-","gene":"EBF1^ENSG00000164330.17","orient":"-","chr":"chr5","lend":"159084666"},"chr":"chr5"}] .

**Comment by brianjohnhaas** [comment]
Sorry for the delayed response - missed this somehow.    With few exceptions, exon region overlap is required for STAR-Fusion to report candidates.  If the alignment falls entirely within an intron or intergenic region, then it's not added as a candidate.  This is a feature that differentiates our RNA-seq transcript-based fusion predictions from DNA-based systems.  In your example, it appears that the match to the RUNX1 gene is within an intron region and lacks overlap with annotated exon features:   https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr21%3A36175046%2D36209045&hgsid=764639917_hmS2jtpUAuu51xkvJRqqv4AKNbmG
