### ISSUE TITLE
Any way to add CDS/coding sequence information with just genes/breakpoint data?

### ISSUE THREAD

**Issue by andreabc** [STAR-Fusion/STAR-Fusion#214]

**Comment by brianjohnhaas** [comment]
Hi,

If you include the parameter --examine_coding_effect
it'll include additional info about the potential fusion sequence info.  It
requires a coding/coding region fusion for this.

best,

~b

On Fri, Jul 10, 2020 at 6:44 PM Andrea <notifications@github.com> wrote:
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by andreabc** [comment]
Thanks Brian, I'm trying to do this after the fusion calling has been done, I don't have the original files. If I 'remake' the star-fusion.fusion_predictions.tsv file with just columns for  #FusionName, LeftGene, LeftBreakpoint, RightGene, RightBreakpoint is there some intermediate command I can call to just add examine_coding_effect? Thanks again!

**Comment by brianjohnhaas** [comment]
Hi Andrea,

The command that gets run in STAR-Fusion to add the coding effect
annotations is:

STAR_FUSION_HOME/FusionAnnotator/util/fusion_to_coding_region_effect.pl
 --fusions $abridged_final_output --genome_lib_dir $genome_lib_dir >
$coding_eff_filename

You can run this on your STAR-Fusion output file, but just be sure that
you're using the same CTAT genome lib leveraged for the earlier STAR-Fusion
run.

best,

~brian

On Sun, Jul 12, 2020 at 4:08 PM Andrea <notifications@github.com> wrote:
>
> Thanks Brian, I'm trying to do this after the fusion calling has been
done, I don't have the original files. If I 'remake' the
star-fusion.fusion_predictions.tsv file with just columns for #FusionName,
LeftGene, LeftBreakpoint, RightGene, RightBreakpoint is there some
intermediate command I can call to just add examine_coding_effect? Thanks
again!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by andreabc** [comment]
Awesome, thank you
