### ISSUE TITLE
remove read-thru transcripts from reference annotations

### ISSUE THREAD

**Issue by brianjohnhaas** [STAR-Fusion/STAR-Fusion#23]
they're confounding.  ex. GOPC--ROS1

**Comment by brianjohnhaas** [comment]
just remove long introns from reference annotation where the connected exons clearly map to two separate genes.

**Comment by ndaniel** [comment]
https://github.com/STAR-Fusion/STAR-Fusion/commit/c0b411ee76e36d081ba7be1d7715c80190bc687f ?
