### ISSUE TITLE
overlapping reads & fusion evidence

### ISSUE THREAD

**Issue by brianjohnhaas** [STAR-Fusion/STAR-Fusion#24]
(From Daniel Nicorici on another thread)

I think that the best and effective strategy here (which is also the simplest) is to use a tool which merges the paired-end reads which overlap before the alignment is done using STAR.

For example, running a tool which merges overlapping paired-end reads, like for example bbmerge.sh (from BBMAP tools) would create two types of input FASTQ files, which are:

paired-ends reads which were not merged (which are actually two FASTQ files) and these can be used as usual for STAR
paired-end reads which are overlapping and are merged (without using GTF file), and which look now like single-end reads (that is one FASTQ file) and this FASTQ file can be given as input to STAR.

**Comment by ndaniel** [comment]
https://github.com/STAR-Fusion/STAR-Fusion/commit/c0b411ee76e36d081ba7be1d7715c80190bc687f ?

**Comment by brianjohnhaas** [comment]
Hi Daniel

It requires updating the genome lib.  I’ve got test results to examine and if they look good I’ll put out the new release.  Should know soon.

Best,

-Brian
(by iPhone)
