### ISSUE TITLE
Detection fusions between genes and other genomic sequences

### ISSUE THREAD

**Issue by jrderuiter** [STAR-Fusion/STAR-Fusion#3]
From the documentation it seems that STAR-Fusion primarily detects fusion between known (annotated) genes. For a project I am working on I am trying to identify fusions between genes and specific splice acceptor/donor sequences that do not belong to an annotated gene. Using other fusion aligners I do find reads that support splicing from genes to/from these SA/SD sequences.

Will STAR-Fusion report these fusions or does it really limit itself to fusions between annotated genes? Would it be possible to allow STAR-Fusion to report these types of fusions?

**Comment by brianjohnhaas** [comment]
Hi Julian,

The latest STAR-Fusion release should detect fusions within exons of
annotated genes even if they don't map precisely to reference annotated
splice junctions. The breakpoint, however, still needs to be within the
range of a known exonic region. If the breakpoint shows up in an intron or
intergenic region, it won't be reported by STAR-Fusion --- though you could
still mine the raw STAR output to find evidence for them.

best,

~brian


On Mon, Jul 27, 2015 at 4:46 AM, Julian de Ruiter <notifications@github.com>
wrote:

> From the documentation it seems that STAR-Fusion primarily detects fusion
> between known (annotated) genes. For a project I am working on I am trying
> to identify fusions between genes and specific splice acceptor/donor
> sequences that do not belong to an annotated gene. Using other fusion
> aligners I do find reads that support splicing from genes to/from these
> SA/SD sequences.
>
> Will STAR-Fusion report these fusions or does it really limit itself to
> fusions between annotated genes? Would it be possible to allow STAR-Fusion
> to report these types of fusions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/3>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by jrderuiter** [comment]
Hi Brian,

Thank you for the quick answer! I am interested in unannotated regions, so that would be more like an intergenic region in your definition. Are you limiting STAR-Fusion to exonic regions to limit the amount of false positives of the approach?

I'll definitely have a look at mining the raw STAR output for my purposes.

Best,
Julian

**Comment by brianjohnhaas** [comment]
Yes, limiting the calls to the annotated exons is to limit the number of
false positives.  I'll look into including options that allow one to
summarize other events for some future release, though, as I can certainly
appreciate the utility of it.

best,

~brian


On Mon, Jul 27, 2015 at 11:24 AM, Julian de Ruiter <notifications@github.com
> wrote:

> Hi Brian,
>
> Thank you for the quick answer! I am interested in unannotated regions, so
> that would be more like an intergenic region in your definition. Are you
> limiting STAR-Fusion to exonic regions to limit the amount of false
> positives of the approach?
>
> I'll definitely have a look at mining the raw STAR output for my purposes.
>
> Best,
> Julian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/3#issuecomment-125243707>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
