### ISSUE TITLE
ERROR: Genome version: 2.7.1a is INCOMPATIBLE with running STAR version: 2.7.5c

### ISSUE THREAD

**Issue by amasden** [STAR-Fusion/STAR-Fusion#303]
Hello, I'm having hard time with issue below:

Feb 22 23:05:31 ..... started STAR run
Feb 22 23:05:31 ..... loading genome

EXITING because of FATAL ERROR: Genome version: 2.7.1a is INCOMPATIBLE with running STAR version: 2.7.5c
SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.4a

Feb 22 23:05:31 ...... FATAL ERROR, exiting

STAR-Fusion version: 1.8.1
--genome_lib_dir: GRCh37_gencode_v19_CTAT_lib_Oct012019.plug-n-play/ctat_genome_lib_build_dir

I also looked up to the site below:
https://github.com/STAR-Fusion/STAR-Fusion/wiki/STAR-Fusion-release-and-CTAT-Genome-Lib-Compatibility-Matrix
but, could not find solutions. Sorry for the naive question, thank you.

**Comment by brianjohnhaas** [comment]
hi,

Here's the software / genome lib compatibility matrix:

https://github.com/STAR-Fusion/STAR-Fusion/wiki/STAR-Fusion-release-and-CTAT-Genome-Lib-Compatibility-Matrix

If you use our corresponding Singularity or Docker image, it should
already have everything you need to run.
https://github.com/STAR-Fusion/STAR-Fusion/wiki#want-to-use-singularity

best,

~brian

On Tue, Feb 22, 2022 at 11:12 PM amasden ***@***.***> wrote:
>
> Hello, I'm having hard time with issue below:
>
> Feb 22 23:05:31 ..... started STAR run
> Feb 22 23:05:31 ..... loading genome
>
> EXITING because of FATAL ERROR: Genome version: 2.7.1a is INCOMPATIBLE with running STAR version: 2.7.5c
> SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.4a
>
> Feb 22 23:05:31 ...... FATAL ERROR, exiting
>
> STAR-Fusion version: 1.8.1
> --genome_lib_dir: GRCh37_gencode_v19_CTAT_lib_Oct012019.plug-n-play/ctat_genome_lib_build_dir
>
> I also looked up to the site below:
> https://github.com/STAR-Fusion/STAR-Fusion/wiki/STAR-Fusion-release-and-CTAT-Genome-Lib-Compatibility-Matrix
> but, could not find solutions. Sorry for the naive questions, thank you.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
