### ISSUE TITLE
promiscuity filter

### ISSUE THREAD

**Issue by annaquaglieri16** [STAR-Fusion/STAR-Fusion#31]
Hi there, 
I was wondering if you could give me a quick explanation of what the promiscuity filter does. Is it looking to see if the same gene is fused with many other genes in the set of my calls? 

Thanks, 

Anna

**Comment by brianjohnhaas** [comment]
Hi

Yes, if a gene is found reported in more than 3 pairs then it'll exclude it.  There should be details about this in our biorxiv paper on star-fusion including more precise details since expression values are also taken into account here.

Best,

-Brian
(by iPhone)

**Comment by annaquaglieri16** [comment]
Thanks Brian, 
Sorry that I missed the paper!

Cheers,
Anna
