### ISSUE TITLE
junction_breakpts_to_genes.txt file contents and use

### ISSUE THREAD

**Issue by tarfy** [STAR-Fusion/STAR-Fusion#311]
Hi,

Would you be able to tell me (or point me in the direction of some documentation for) the column headers for the junction_breakpts_to_genes.txt file please? In particular I am wondering about the information in columns 22 and 23.

I have a panel of genes that I am interested in and when I used a validation sample I found that some expected fusions were not present in the star-fusion.fusion_predictions.tsv file. When I grep for the "missing" fusions of interest in the junction_breakpts_to_genes.txt file there are some reads mapping to those gene pairs. My plan was to pull out genes of interest which are represented in the junction_breakpts_to_genes.txt file and use the corresponding fusion as input for FusionInspector. Do you think this is a worthwhile approach?

Thanks!

**Comment by brianjohnhaas** [comment]
Hi,

My guess is that there was insufficient read alignment evidence counts to
report them.  There are the following options that could help with
reporting them if that's the case:

#

#    --max_sensitivity                     includes options:
--min_junction_reads 0 --min_sum_frags 1 --require_LDAS 0
--min_spanning_frags_only 1 --min_novel_junction_support 1 --skip_FFPM --

no_single_fusion_per_breakpoint --skip_EM

#

#    --full_Monty                          includes max sensitivity and
disables filters via: --max_promiscuity 1000000 --min_pct_dom_promiscuity 1
--min_alt_pct_junction 1e-3 --no_annotation_filter --no_RT_artifact_filter

#


Another thing to do is as you mention - running FusionInspector directly
and give the expected fusion set as the candidate list.  Just be sure the
gene symbols for the target fusion genes are provided as indicated in the
$CTAT_GENOME_LIB/ref_annot.gtf.gene_spans file so they'll be properly
recognized.  Sometimes the gene symbols folks use are different for various
reasons (synonyms, annotation versions, etc.)

For the formatting of the chimeric junctions file, the most recent version
of the STAR manual (pdf) should have all the details. I vaguely remember us
updating it. Let me know if you don't find what you're looking for, though.

hope this helps,

~b




On Wed, Apr 27, 2022 at 11:16 AM tarfy ***@***.***> wrote:
>
> Hi,
>
> Would you be able to tell me (or point me in the direction of some
documentation for) the column headers for the
junction_breakpts_to_genes.txt file please? In particular I am wondering
about the information in columns 22 and 23.
>
> I have a panel of genes that I am interested in and when I used a
validation sample I found that some expected fusions were not present in
the star-fusion.fusion_predictions.tsv file. When I grep for the "missing"
fusions of interest in the junction_breakpts_to_genes.txt file there are
some reads mapping to those gene pairs. My plan was to pull out genes of
interest which are represented in the junction_breakpts_to_genes.txt file
and use the corresponding fusion as input for FusionInspector. Do you think
this is a worthwhile approach?
>
> Thanks!
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by tarfy** [comment]
Hi Brian,

Thanks very much for your help. I think you're right about the insufficient read alignment evidence. I tried the --max-sensitvity and --full-monty options and there were a lot of false positives, which is to be expected I guess. 

Is it possible to run FusionInspector where you only specify one gene in the fusion pair?

I read the explanation in the manual about the chimeric junction file but the junction_breakpts_to_genes.txt file has two extra columns which contain the gene names that I am not sure about. This is one line from my junction_breakpts_to_genes.txt file. Information for gene A is in column 22 and for gene B is in column 23:

chr10   43116583        -       chr10   59906121        +       2       1       0       NB551666:23:H2MK3BGXK:3:22512:22843:7361        43116584        55S63M  59906122  63S55M  1       118     62      116     116     1       GRPundef        [{"**gene_id":"RET**^ENSG00000165731.20","sense_or_antisense":"antisense","chr":"chr10","pt_align":"43116584","pt_exon":"43116584","anchor_length":63,"exon":{"orient":"+","lend":"43116584","token":"RET^ENSG00000165731.20^43116584^43116731^+","gene":"RET^ENSG00000165731.20","rend":"43116731","chr":"chr10"},"delta":0}]  [{"pt_exon":"59906122","exon":{"orient":"-","chr":"chr10","token":"CCDC6^ENSG00000108091.11^59906122^59906556^-","gene":"CCDC6^ENSG00000108091.11","lend":"59906122","rend":"59906556"},"delta":0,"anchor_length":55,"chr":"chr10","pt_align":"59906122","sense_or_antisense":"antisense","**gene_id":"CCDC6**^ENSG00000108091.11"}]

For another line, information about both genes A and B are in column 22 and column 23 is empty:

chr10   21624679        +       chr2    32916471        -       -1      0       0       NB551666:23:H2MK3BGXK:3:12511:22896:1690        21624605        74M     32916396  75M     8       149     72      133     135     0       GRPundef        [{**"gene_id":"MLLT10**^ENSG00000078403.17","sense_or_antisense":"sense","chr":"chr10","pt_align":21624678,"pt_exon":"21624749","exon":{"chr":"chr10","gene":"MLLT10^ENSG00000078403.17","token":"MLLT10^ENSG00000078403.17^21624667^21624749^+","lend":"21624667","rend":"21624749","orient":"+"},"delta":71,"anchor_length":74},{"exon":{"orient":"-","token":"HNRNPRP1^ENSG00000223984.1^21624592^21626286^-","lend":"21624592","gene":"HNRNPRP1^ENSG00000223984.1","rend":"21626286","chr":"chr10"},"delta":1608,"anchor_length":74,"pt_exon":"21626286","pt_align":21624678,"chr":"chr10","sense_or_antisense":"antisense",**"gene_id":"HNRNPRP1**^ENSG00000223984.1"}]    .

It would be great if you could help me interpret the difference between these breakpoints.

Thanks again!

**Comment by tarfy** [comment]
Thanks for the explanation and for all your help!
