### ISSUE TITLE
Docerkfile does not update in v1.2.0

### ISSUE THREAD

**Issue by ianyfchang** [STAR-Fusion/STAR-Fusion#37]
The version number in the Dockerfile of STAR-Fusion-v1.2.0.FULL.tar.gz is 1.1.0

**Comment by brianjohnhaas** [comment]
It’s 1.2.  I just forgot to update the version string in the installed software.  Apologies

-Brian
(by iPhone)

**Comment by ianyfchang** [comment]
Thanks!
