### ISSUE TITLE
Tarball file name for STAR-Fusion v1.13.0 Release

### ISSUE THREAD

**Issue by alexey-larionov** [STAR-Fusion/STAR-Fusion#403]
Somehow the tarball name for STAR-Fusion-v1.13.0 is STAR-Fusion.v0.13.0.FULL.tar.gz
Please note the v.0 bit, which supposedly should be v.1
Of course, it's a minor and inconsequential typo, but may be slightly confusing

The full name for the file in question:
https://github.com/STAR-Fusion/STAR-Fusion/releases/download/STAR-Fusion-v1.13.0/STAR-Fusion.v0.13.0.FULL.tar.gz

**Comment by brianjohnhaas** [comment]
Thanks for letting me know!  It's now corrected. Much appreciated!
