### ISSUE TITLE
repeating fusion events at fusion-predict step

### ISSUE THREAD

**Issue by l337x911** [STAR-Fusion/STAR-Fusion#5]
Dear Brian,

I am finding that fusion events are being repeated in separate rows, and are being incorrectly labeled. 
For example, in the below excerpt from a star-fusion.fusion_candidates.final file, there are two rows calling a BCR-ABL1 fusion with identical breakpoints, and spanning reads. However, The junction reads are distinct between the two rows, and the splice type is different.

BCR--ABL1       36      23      ONLY_REF_SPLICE BCR^ENSG00000186716.15  chr22:23632600:+        ABL1^ENSG00000097007.13 chr9:133729451:+ 
BCR--ABL1       22      23      INCL_NON_REF_SPLICE     BCR^ENSG00000186716.15  chr22:23632600:+        ABL1^ENSG00000097007.13 chr9:133729451:+

These rows appear in the star-fusion.fusion_candidates.preliminary file, so I'm assuming that there is something strange in the STAR-Fusion.predict step. I am running STAR-Fusion 0.5.1, and observed this bug for a few different samples. Any suggestions for what's going on?

**Comment by brianjohnhaas** [comment]
Hi,

Yes, this does look like a bug...  Can you provide me with your
Chimeric.out.junctions file for that sample?  I'll troubleshoot it and fix
whatever the issue is.

many thanks,

~brian


On Mon, Oct 19, 2015 at 12:45 PM, Anand D. Patel <notifications@github.com>
wrote:

> Dear Brian,
>
> I am finding that fusion events are being repeated in separate rows, and
> are being incorrectly labeled.
> For example, in the below excerpt from a
> star-fusion.fusion_candidates.final file, there are two rows calling a
> BCR-ABL1 fusion with identical breakpoints, and spanning reads. However,
> The junction reads are distinct between the two rows, and the splice type
> is different.
>
> BCR--ABL1 36 23 ONLY_REF_SPLICE BCR^ENSG00000186716.15 chr22:23632600:+
> ABL1^ENSG00000097007.13 chr9:133729451:+
> BCR--ABL1 22 23 INCL_NON_REF_SPLICE BCR^ENSG00000186716.15
> chr22:23632600:+ ABL1^ENSG00000097007.13 chr9:133729451:+
>
> I am running STAR-Fusion 0.5.1, and observed this bug for a few different
> samples. Any suggestions for what's going on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/5>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by l337x911** [comment]
Thanks for the fast response!

I've attached the "junctions" file.
STAR-Fusion was ran using the Hg19_CTAT_resource_lib, and the following
parameters:
 --min_novel_junction_support 10 -E 0.0001 --aggregate_novel_junction_dist
10

-Anand

**Comment by brianjohnhaas** [comment]
Thanks!  I didn't get the attachment... could you send it to me directly?
 (off list if needed)

many thx,

~b

On Mon, Oct 19, 2015 at 3:21 PM, Anand D. Patel <notifications@github.com>
wrote:

> Thanks for the fast response!
>
> I've attached the "junctions" file.
> STAR-Fusion was ran using the Hg19_CTAT_resource_lib, and the following
> parameters:
> --min_novel_junction_support 10 -E 0.0001 --aggregate_novel_junction_dist
> 10
>
> -Anand
>
> On Mon, Oct 19, 2015 at 9:59 AM Brian Haas <notifications@github.com>
> wrote:
>
> > Hi,
> >
> > Yes, this does look like a bug... Can you provide me with your
> > Chimeric.out.junctions file for that sample? I'll troubleshoot it and fix
> > whatever the issue is.
> >
> > many thanks,
> >
> > ~brian
> >
> >
> > On Mon, Oct 19, 2015 at 12:45 PM, Anand D. Patel <
> notifications@github.com
> > >
> > wrote:
> >
> > > Dear Brian,
> > >
> > > I am finding that fusion events are being repeated in separate rows,
> and
> > > are being incorrectly labeled.
> > > For example, in the below excerpt from a
> > > star-fusion.fusion_candidates.final file, there are two rows calling a
> > > BCR-ABL1 fusion with identical breakpoints, and spanning reads.
> However,
> > > The junction reads are distinct between the two rows, and the splice
> type
> > > is different.
> > >
> > > BCR--ABL1 36 23 ONLY_REF_SPLICE BCR^ENSG00000186716.15 chr22:23632600:+
> > > ABL1^ENSG00000097007.13 chr9:133729451:+
> > > BCR--ABL1 22 23 INCL_NON_REF_SPLICE BCR^ENSG00000186716.15
> > > chr22:23632600:+ ABL1^ENSG00000097007.13 chr9:133729451:+
> > >
> > > I am running STAR-Fusion 0.5.1, and observed this bug for a few
> different
> > > samples. Any suggestions for what's going on?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/STAR-Fusion/STAR-Fusion/issues/5>.
> > >
> >
> >
> >
> > --
> > --
> > Brian J. Haas
> > The Broad Institute
> > http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/STAR-Fusion/STAR-Fusion/issues/5#issuecomment-149281137
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/5#issuecomment-149318636>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
I'm pretty sure I found and fixed the bug.  Could you pull the latest code:

   git clone --recursive https://github.com/STAR-Fusion/STAR-Fusion.git

and give it a whirl?

I'll do some more testing with it before putting out the release.

Also, is it OK with you if I include your bcr-abl example in my test kit?  (basically, just pulling the bcr-abl subset out of your junctions file).

many thanks!!!

~brian

**Comment by brianjohnhaas** [comment]
Test results looked good, and I just posted the v0.5.2 release.

Please let me know if I can add the bcr-abl entries to the test kit.  If you'd prefer I don't, that's entirely fine.

much appreciated.

**Comment by l337x911** [comment]
Verified. The v0.5.2 release looks great! Thanks for the fast response.
Unfortunately, I am not the owner of the data. I'd prefer not having the bcr-abl entries added to the test kit.
