### ISSUE TITLE
example parameters

### ISSUE THREAD

**Issue by HIM72** [STAR-Fusion/STAR-Fusion#6]
Hi, 
The example code given on the wiki page for STAR alignment how were the parameters 
decided? 
Would doing 2-pass alignment with custom junction file give better results?
Thank you.

**Comment by brianjohnhaas** [comment]
The parameters were initially based on Nicoli Stransky's published work and then modified by Alex and I during testing and development. Using a custom junction file could potentially  help if there are fusions containing splice or fusion break points not in the ref annotation set used during the genome build.  We've had excellent sensitivity for all known cancer fusions we've tested thus far, though.  If you're finding certain ones lacking, I'd be happy to explore them further.

Best,

-Brian
(by iPhone)

**Comment by HIM72** [comment]
Thank you for your prompt reply.
I see that the sciedpipeR directory is empty. does it have to be installed in this directory to work?
Thank you.

**Comment by brianjohnhaas** [comment]
Hi,

If you pull the code from github via git clone, be sure to do

   git clone --recursive

and this will pull down the submodules.

If you're downloading the pre-bundled source, be sure to get the tar.gz
file with 'FULL' in the name.

best,

~brian


On Wed, Jan 13, 2016 at 8:44 PM, HIM72 <notifications@github.com> wrote:

> Thank you for your prompt reply.
> I see that the sciedpipeR directory is empty. does it have to be installed
> in this directory to work?
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/6#issuecomment-171498366>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
