### ISSUE TITLE
'FFPM' relative to the expression of fusion partners?

### ISSUE THREAD

**Issue by plijnzaad** [STAR-Fusion/STAR-Fusion#62]
Would it be difficult (and meaningful) to include the total number of (non-fusion related) reads mapping to either of the fusion partners? It would seem an obvious measure to relate the occurrence of fusion reads to the expression of the wt alleles.  Edit: I browsed around a bit, I think the FAF (fusion allele frequency) would address this. (see also issue #43 )

**Comment by brianjohnhaas** [comment]
Yes.  This analysis is included in fusion inspector.  The prod code uses FAF (fusion allelic fraction) and the devel code updates this to FAR (ratio), which will go in the next release (soon).

Best 

-Brian
(by iPhone)

**Comment by plijnzaad** [comment]
(ah, postings crossing :-)
