### ISSUE TITLE
How to install Pipeliner?

### ISSUE THREAD

**Issue by jlee110** [STAR-Fusion/STAR-Fusion#68]
cpan[2]> install Pipeliner
Reading '/home/jlee110/.cpan/Metadata'
  Database was generated on Wed, 02 May 2018 15:17:03 GMT
Warning: Cannot install Pipeliner, don't know what it is.
Try the command

    i /Pipeliner/

to find objects with matching identifiers.

cpan[3]> 

I'd appreciate it if anyone could show me how to install this module.

Thanks!

**Comment by brianjohnhaas** [comment]
Hi

You shouldn’t need to do this.  Note that star fusion needs to be run from within the full software package.  You can’t copy the script outside and then run it as it’s tied to other pieces of the code in surrounding directories 

-Brian
(by iPhone)
