### ISSUE TITLE
Issue with prep_genome_lib.pl

### ISSUE THREAD

**Issue by annaquaglieri16** [STAR-Fusion/STAR-Fusion#7]
I am trying to prepare the files to STAR-fusion but I keep having trouble running prep_genome_lib.pl.

My code is 
/home/users/allstaff/quaglieri.a/software/STAR-Fusion/FusionFilter/prep_genome_lib_new.pl \
--genome_fa genome.fa\
--gtf genes_known_chrom.gtf\
--blast_pairs blast_pairs.outfmt6.gz\
--output_dir . \
--cdna_fa cDNA_hg19_seqs.fa \
--gmap_build

And the only output that I get is 
###### 
# 
# Required by: STAR-Fusion and FusionInspector
# 
# --genome_fa  <string>           genome fasta file
# 
# --gtf <string>                  transcript structure annotation
# Note: can restrict to coding genes
# 
# --blast_pairs <string>          transcript blastn results
# in BLAST+ '-outfmt 6'  format and gzipped!
# Note: gene symbols must replace transcript IDs.
# 
# Required by STAR
# 
# --max_readlength <int>          max length for an individual RNA-Seq read (ie. default: 100)
# 
# Misc options:
# 
# --output_dir <string>           output directory
# 
# --CPU <int>                     number of threads (defalt: 4)
# 
# --gmap_build                    include gmap_build (for use w/ DISCASM/GMAP-fusion)
# 
###### 

And the code is not running. 
Do you have any suggestion?
Thank you a lot, 
Anna

**Comment by brianjohnhaas** [comment]
Hi,

Please set the output directory to another area other than the current
directory and give it another try.

best,

~brian


On Mon, May 2, 2016 at 10:15 AM, annaquaglieri16 <notifications@github.com>
wrote:

> I am trying to prepare the files to STAR-fusion but I keep having trouble
> running prep_genome_lib.pl.
>
> My code is
> /home/users/allstaff/quaglieri.a/software/STAR-Fusion/FusionFilter/
> prep_genome_lib_new.pl \
> --genome_fa genome.fa\
> --gtf genes_known_chrom.gtf\
> --blast_pairs blast_pairs.outfmt6.gz\
> --output_dir . \
> --cdna_fa cDNA_hg19_seqs.fa \
> --gmap_build
>
> And the only output that I get is
>
>
> ##################################################################################
> #
> Required by: STAR-Fusion and FusionInspector
>
> #
> --genome_fa genome fasta file
>
> #
> --gtf transcript structure annotation Note: can restrict to coding genes
>
> #
> --blast_pairs transcript blastn results in BLAST+ '-outfmt 6' format and
> gzipped! Note: gene symbols must replace transcript IDs.
>
> #
> Required by STAR
>
> #
> --max_readlength max length for an individual RNA-Seq read (ie. default:
> 100)
>
> #
> Misc options:
>
> #
> --output_dir output directory
>
> #
> --CPU number of threads (defalt: 4)
>
> #
> --gmap_build include gmap_build (for use w/ DISCASM/GMAP-fusion)
>
> #
>
> ##################################################################################
>
> And the code is not running.
> Do you have any suggestion?
> Thank you a lot,
> Anna
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/7>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by annaquaglieri16** [comment]
Thank you Brian!!! it works now
All the best
Anna

**Comment by brianjohnhaas** [comment]
Great!  Thanks for the update,

~brian


On Tue, May 3, 2016 at 7:47 PM, annaquaglieri16 <notifications@github.com>
wrote:

> Thank you Brian!!! it works now
> All the best
> Anna
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/7#issuecomment-216700700>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
