### ISSUE TITLE
FusionInspector error

### ISSUE THREAD

**Issue by BGIHENG** [STAR-Fusion/STAR-Fusion#74]
Hi：
There is a error ：
Can't exec "STAR-Fusion-v1.3.2/FusionInspector/FusionInspector": No such file or directory at STAR-Fusion-v1.3.2/PerlLib/Pipeliner.pm line 170

Could you tell me how solve it.

Thanks !

**Comment by brianjohnhaas** [comment]
Hi

You need to download the ‘FULL’ version that contains all the submodules.  Let me know if you have trouble with this.  It should be one of the download targets.  The others are auto generated by GitHub and lack submodules.

Best,

-Brian
(by iPhone)
