### ISSUE TITLE
New Gencode Annotation for Human

### ISSUE THREAD

**Issue by JLCCI** [STAR-Fusion/STAR-Fusion#8]
Many thanks for the great software.

Any chance you could upload a new CTAT recourse library based on newest human gencode annotation (GRCh38 + v24)?

Many thanks!

**Comment by brianjohnhaas** [comment]
Will do soon.

On Wed, May 25, 2016 at 12:25 AM, JLCCI <notifications@github.com> wrote:

> Many thanks for the great software.
>
> Any chance you could upload a new CTAT recourse library based on newest
> gencode annotation (GRCh38 + v24)?
>
> Many thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/8>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by JLCCI** [comment]
Fantastic, thank you. Any chance for a rough estimate when you will have a moment to add it?

**Comment by brianjohnhaas** [comment]
I'll see if I can get something to you later today.

On Sun, May 29, 2016 at 10:26 PM, JLCCI <notifications@github.com> wrote:

> Fantastic, thank you. Any chance for a rough estimate when you will have a
> moment to add it?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/8#issuecomment-222399930>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX-CQIPTOHq31Bolb35XnY6vnulFpks5qGkrvgaJpZM4ImJnn>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by brianjohnhaas** [comment]
Here's a resource data set built for testing out gencode v24:

ftp://ftp.broadinstitute.org/pub/users/bhaas/tmp/GRCh38_gencode_v24_ctat_beta.tar.gz

Note, it's a big file (26G), but it contains everything already indexed
(star index, blast pairs indexed), and you might be able to just point to
it with the --genome_lib_dir parameter w/out having to rebuild anything.

I ran a few small tests on it, but haven't thoroughly explored it, so I'm
calling it 'beta', and please let me know if you run into any issues.

best,

~brian

**Comment by JLCCI** [comment]
Thanks you so much for a prompt reply and uploading the files, it is very much appreciated.

I have a lot of samples to run through the pipeline and will be happy to report any bugs if they appear. Keep up the good work!

**Comment by brianjohnhaas** [comment]
Great to hear!

many thanks!

~b

On Tue, May 31, 2016 at 9:51 PM, JLCCI <notifications@github.com> wrote:

> Thanks you so much for a prompt reply and uploading the files, it is very
> much appreciated.
>
> I have a lot of samples to run through the pipeline and will be happy to
> report any bugs if they appear. Keep up the good work!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/8#issuecomment-222871638>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX9frjeRINLaDaca-RATkahqQ8is8ks5qHOW9gaJpZM4ImJnn>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by JLCCI** [comment]
Hi Brain, small issue:

-- Skipping CMD: STAR --genomeDir /path/genome/fusion_index/ref_genome.fa.star.idx  --readFilesIn /path/lung_cancer/data/rna_seq/fusion/../raw/Sample1_R1.fq /path/lung_cancer/data/rna_seq/fusion/../raw/Sample1_R2.fq  --twopassMode Basic  --outReadsUnmapped None  --chimSegmentMin 12  --chimJunctionOverhangMin 12  --alignSJDBoverhangMin 10  --alignMatesGapMax 200000  --alignIntronMax 200000  --chimSegmentReadGapMax 3  --alignSJstitchMismatchNmax 5 -1 5 5  --runThreadN 4 --limitBAMsortRAM 31532137230  --outSAMtype BAM SortedByCoordinate , checkpoint exists.
* Running CMD: /path/software/STAR-master/STAR-Fusion/util/STAR-Fusion.predict  -J Chimeric.out.junction  --genome_lib_dir /path/genome/fusion_index  --min_junction_reads 1  --min_sum_frags 2  --min_novel_junction_support 3  -O /path/lung_cancer/data/rna_seq/fusion/star-fusion 
-parsing GTF file: /path/genome/fusion_index/ref_annot.gtf
Error, cannot get transcript_id from gene_id "ENSG00000223972.5"; gene_type "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2"; of line
chr1    HAVANA  gene    11869   14409   .       +       .       gene_id "ENSG00000223972.5"; gene_type "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2"; at /path/software/STAR-master/STAR-Fusion/util/../PerlLib/GTF_utils.pm line 111
        GTF_utils::GTF_to_gene_objs('/path/genome/fusion_index/ref_annot.gtf') called at /path/software/STAR-master/STAR-Fusion/util/../PerlLib/GTF_utils.pm line 30
        GTF_utils::index_GTF_gene_objs_from_GTF('/path/genome/fusion_index/ref_annot.gtf', 'HASH(0x13dbb98)') called at /path/software/STAR-master/STAR-Fusion/util/../PerlLib/GTF_utils.pm line 20
        GTF_utils::index_GTF_gene_objs('/path/genome/fusion_index/ref_annot.gtf', 'HASH(0x13dbb98)') called at /path/software/STAR-master/STAR-Fusion/util/STAR-Fusion.predict line 370
        main::parse_GTF_features('/path/genome/fusion_index/ref_annot.gtf', 'HASH(0x1c6a8b0)', 'HASH(0x1c6a8e0)') called at /path/software/STAR-master/STAR-Fusion/util/STAR-Fusion.predict line 112
Error, cmd: /path/software/STAR-master/STAR-Fusion/util/STAR-Fusion.predict  -J Chimeric.out.junction  --genome_lib_dir /path/genome/fusion_index  --min_junction_reads 1  --min_sum_frags 2  --min_novel_junction_support 3  -O /path/lung_cancer/data/rna_seq/fusion/star-fusion  died with ret 6400 at /path/software/STAR-master/STAR-Fusion/PerlLib/Pipeliner.pm line 79
        Pipeliner::run('Pipeliner=HASH(0x18a5d68)') called at /path/software/STAR-master/STAR-Fusion/STAR-Fusion line 259

I presume all non-protein coding genes should be removed from the reference? I'm using the reference you provided.

Many thanks for help!

**Comment by brianjohnhaas** [comment]
I think this is something I fixed in the devel code but haven't put out a
new release yet.  Can you try

   git clone --recursive

 to pull the latest master branch from github and see if it's still a
problem?

thx!

~b

On Sun, Jun 19, 2016 at 11:45 PM, JLCCI <notifications@github.com> wrote:

> Hi Brain, small issue:
>
> -- Skipping CMD: STAR --genomeDir
> /path/genome/fusion_index/ref_genome.fa.star.idx --readFilesIn
> /path/lung_cancer/data/rna_seq/fusion/../raw/Sample1_R1.fq
> /path/lung_cancer/data/rna_seq/fusion/../raw/Sample1_R2.fq --twopassMode
> Basic --outReadsUnmapped None --chimSegmentMin 12 --chimJunctionOverhangMin
> 12 --alignSJDBoverhangMin 10 --alignMatesGapMax 200000 --alignIntronMax
> 200000 --chimSegmentReadGapMax 3 --alignSJstitchMismatchNmax 5 -1 5 5
> --runThreadN 4 --limitBAMsortRAM 31532137230 --outSAMtype BAM
> SortedByCoordinate , checkpoint exists.
>
>    - Running CMD:
>    /path/software/STAR-master/STAR-Fusion/util/STAR-Fusion.predict -J
>    Chimeric.out.junction --genome_lib_dir /path/genome/fusion_index
>    --min_junction_reads 1 --min_sum_frags 2 --min_novel_junction_support 3 -O
>    /path/lung_cancer/data/rna_seq/fusion/star-fusion -parsing GTF file:
>    /path/genome/fusion_index/ref_annot.gtf Error, cannot get transcript_id
>    from gene_id "ENSG00000223972.5"; gene_type
>    "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name
>    "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2"; of line chr1 HAVANA
>    gene 11869 14409 . + . gene_id "ENSG00000223972.5"; gene_type
>    "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name
>    "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2"; at
>    /path/software/STAR-master/STAR-Fusion/util/../PerlLib/GTF_utils.pm line
>    111 GTF_utils::GTF_to_gene_objs('/path/genome/fusion_index/ref_annot.gtf')
>    called at
>    /path/software/STAR-master/STAR-Fusion/util/../PerlLib/GTF_utils.pm line 30
>    GTF_utils::index_GTF_gene_objs_from_GTF('/path/genome/fusion_index/ref_annot.gtf',
>    'HASH(0x13dbb98)') called at
>    /path/software/STAR-master/STAR-Fusion/util/../PerlLib/GTF_utils.pm line 20
>    GTF_utils::index_GTF_gene_objs('/path/genome/fusion_index/ref_annot.gtf',
>    'HASH(0x13dbb98)') called at
>    /path/software/STAR-master/STAR-Fusion/util/STAR-Fusion.predict line 370
>    main::parse_GTF_features('/path/genome/fusion_index/ref_annot.gtf',
>    'HASH(0x1c6a8b0)', 'HASH(0x1c6a8e0)') called at
>    /path/software/STAR-master/STAR-Fusion/util/STAR-Fusion.predict line 112
>    Error, cmd: /path/software/STAR-master/STAR-Fusion/util/STAR-Fusion.predict
>    -J Chimeric.out.junction --genome_lib_dir /path/genome/fusion_index
>    --min_junction_reads 1 --min_sum_frags 2 --min_novel_junction_support 3 -O
>    /path/lung_cancer/data/rna_seq/fusion/star-fusion died with ret 6400 at
>    /path/software/STAR-master/STAR-Fusion/PerlLib/Pipeliner.pm line 79
>    Pipeliner::run('Pipeliner=HASH(0x18a5d68)') called at
>    /path/software/STAR-master/STAR-Fusion/STAR-Fusion line 259
>
> I presume all non-protein coding genes should be removed from the
> reference? I'm using the reference you provided.
>
> Many thanks for help!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/8#issuecomment-227044879>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX68NTik90rYcRKWTeiSIh6CJpJXbks5qNgzpgaJpZM4ImJnn>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by JLCCI** [comment]
Works perfectly now, thank you!
