### ISSUE TITLE
Issue getting test script to run

### ISSUE THREAD

**Issue by jtpoirier** [STAR-Fusion/STAR-Fusion#9]
I get the below error message when trying to run the test script. Not sure what the exact problem is, but I did install both perl modules into my PERL5LIB.

-bash-4.1$ /usr/bin/env perl --version

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

-bash-4.1$ ./runMe.kickstart.sh
CMD: mkdir -p /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir
- Running CMD: /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict  -J /ifs/e63data/poirierj/bin/STAR-Fusion/testing/__kickstart_data/Chimeric.out.junction  --genome_lib_dir /ifs/e63data/poirierj/bin/resources/GRCh38_gencode_v23_CTAT_lib  --min_junction_reads 1  --min_sum_frags 2  --min_novel_junction_support 3  -O /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir/star-fusion 
  Can't load '/ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/x86_64-linux-thread-multi/auto/DB_File/DB_File.so' for module DB_File: libdb-4.3.so: cannot open shared object file: No such file or directory at /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/XSLoader.pm line 70.
  at /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/x86_64-linux-thread-multi/DB_File.pm line 255.
  Compilation failed in require at /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/TiedHash.pm line 6.
  BEGIN failed--compilation aborted at /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/TiedHash.pm line 6.
  Compilation failed in require at /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/base.pm line 99.
  ...propagated at /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/base.pm line 108.
  BEGIN failed--compilation aborted at /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/Gene_obj_indexer.pm line 6.
  Compilation failed in require at /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict line 16.
  BEGIN failed--compilation aborted at /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict line 16.
  Error, cmd: /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict  -J /ifs/e63data/poirierj/bin/STAR-Fusion/testing/__kickstart_data/Chimeric.out.junction  --genome_lib_dir /ifs/e63data/poirierj/bin/resources/GRCh38_gencode_v23_CTAT_lib  --min_junction_reads 1  --min_sum_frags 2  --min_novel_junction_support 3  -O /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir/star-fusion  died with ret 512 at /ifs/e63data/poirierj/bin/STAR-Fusion/PerlLib/Pipeliner.pm line 79.
  Pipeliner::run(Pipeliner=HASH(0x13117a0)) called at ../STAR-Fusion line 259

**Comment by brianjohnhaas** [comment]
Hi,

You'll need to install this:
http://search.cpan.org/~pmqs/DB_File-1.838/DB_File.pm

best,

~b

On Tue, Jun 14, 2016 at 2:22 PM, jtpoirier <notifications@github.com> wrote:

> I get the below error message when trying to run the test script. Not sure
> what the exact problem is, but I did install both perl modules into my
> PERL5LIB.
>
> -bash-4.1$ /usr/bin/env perl --version
>
> This is perl 5, version 22, subversion 0 (v5.22.0) built for
> x86_64-linux-thread-multi
>
> -bash-4.1$ ./runMe.kickstart.sh
> CMD: mkdir -p
> /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir
>
>    - Running CMD:
>    /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict -J
>    /ifs/e63data/poirierj/bin/STAR-Fusion/testing/__kickstart_data/Chimeric.out.junction
>    --genome_lib_dir
>    /ifs/e63data/poirierj/bin/resources/GRCh38_gencode_v23_CTAT_lib
>    --min_junction_reads 1 --min_sum_frags 2 --min_novel_junction_support 3 -O
>    /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir/star-fusion
>    Can't load
>    '/ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/x86_64-linux-thread-multi/auto/DB_File/DB_File.so'
>    for module DB_File: libdb-4.3.so: cannot open shared object file: No
>    such file or directory at
>    /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/XSLoader.pm line 70.
>    at
>    /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/x86_64-linux-thread-multi/DB_File.pm
>    line 255. Compilation failed in require at
>    /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/TiedHash.pm line 6.
>    BEGIN failed--compilation aborted at
>    /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/TiedHash.pm line 6.
>    Compilation failed in require at
>    /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/base.pm line 99.
>    ...propagated at /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/
>    base.pm line 108. BEGIN failed--compilation aborted at
>    /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/Gene_obj_indexer.pm
>    line 6. Compilation failed in require at
>    /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict line 16.
>    BEGIN failed--compilation aborted at
>    /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict line 16.
>    Error, cmd: /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict
>    -J
>    /ifs/e63data/poirierj/bin/STAR-Fusion/testing/__kickstart_data/Chimeric.out.junction
>    --genome_lib_dir
>    /ifs/e63data/poirierj/bin/resources/GRCh38_gencode_v23_CTAT_lib
>    --min_junction_reads 1 --min_sum_frags 2 --min_novel_junction_support 3 -O
>    /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir/star-fusion
>    died with ret 512 at
>    /ifs/e63data/poirierj/bin/STAR-Fusion/PerlLib/Pipeliner.pm line 79.
>    Pipeliner::run(Pipeliner=HASH(0x13117a0)) called at ../STAR-Fusion line 259
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/9>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX5qWWVOLa1aYCeY3GaoygQTH6d5dks5qLvFbgaJpZM4I1nWL>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by jtpoirier** [comment]
Brian,

I have both recommended perl modules installed. It’s possible I don’t have the db4 .so

-bash-4.1$ cpan -l | grep DB_File
DB_File 1.835
DB_File 1.835
site_perl::DB_File 1.838
DB_File 1.835
DB_File 1.838
DB_File 1.838
DB_File 1.835
DB_File 1.835
-bash-4.1$ cpan -l | grep Interval
site_perl::Set::IntervalTree 0.10
Set::IntervalTree 0.10
Set::IntervalTree 0.10

On Jun 14, 2016, at 3:39 PM, Brian Haas <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

You'll need to install this:
http://search.cpan.org/~pmqs/DB_File-1.838/DB_File.pm

best,

~b

On Tue, Jun 14, 2016 at 2:22 PM, jtpoirier <notifications@github.com<mailto:notifications@github.com>> wrote:

> I get the below error message when trying to run the test script. Not sure
> what the exact problem is, but I did install both perl modules into my
> PERL5LIB.
>
> -bash-4.1$ /usr/bin/env perl --version
>
> This is perl 5, version 22, subversion 0 (v5.22.0) built for
> x86_64-linux-thread-multi
>
> -bash-4.1$ ./runMe.kickstart.sh
> CMD: mkdir -p
> /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir
>
> - Running CMD:
> /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict -J
> /ifs/e63data/poirierj/bin/STAR-Fusion/testing/__kickstart_data/Chimeric.out.junction
> --genome_lib_dir
> /ifs/e63data/poirierj/bin/resources/GRCh38_gencode_v23_CTAT_lib
> --min_junction_reads 1 --min_sum_frags 2 --min_novel_junction_support 3 -O
> /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir/star-fusion
> Can't load
> '/ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/x86_64-linux-thread-multi/auto/DB_File/DB_File.so'
> for module DB_File: libdb-4.3.so: cannot open shared object file: No
> such file or directory at
> /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/XSLoader.pm line 70.
> at
> /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/x86_64-linux-thread-multi/DB_File.pm
> line 255. Compilation failed in require at
> /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/TiedHash.pm line 6.
> BEGIN failed--compilation aborted at
> /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/TiedHash.pm line 6.
> Compilation failed in require at
> /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/base.pm line 99.
> ...propagated at /ifs/e63data/poirierj/bin/miniconda3/lib/perl5/5.22.0/
> base.pm line 108. BEGIN failed--compilation aborted at
> /ifs/e63data/poirierj/bin/STAR-Fusion/util/../PerlLib/Gene_obj_indexer.pm
> line 6. Compilation failed in require at
> /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict line 16.
> BEGIN failed--compilation aborted at
> /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict line 16.
> Error, cmd: /ifs/e63data/poirierj/bin/STAR-Fusion/util/STAR-Fusion.predict
> -J
> /ifs/e63data/poirierj/bin/STAR-Fusion/testing/__kickstart_data/Chimeric.out.junction
> --genome_lib_dir
> /ifs/e63data/poirierj/bin/resources/GRCh38_gencode_v23_CTAT_lib
> --min_junction_reads 1 --min_sum_frags 2 --min_novel_junction_support 3 -O
> /ifs/e63data/poirierj/bin/STAR-Fusion/testing/star_fusion_kickstarted_outdir/star-fusion
> died with ret 512 at
> /ifs/e63data/poirierj/bin/STAR-Fusion/PerlLib/Pipeliner.pm line 79.
> Pipeliner::run(Pipeliner=HASH(0x13117a0)) called at ../STAR-Fusion line 259
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/9>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVX5qWWVOLa1aYCeY3GaoygQTH6d5dks5qLvFbgaJpZM4I1nWL>
> .
>



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/STAR-Fusion/STAR-Fusion/issues/9#issuecomment-225992784>, or mute the thread<https://github.com/notifications/unsubscribe/AGTXNz0UdCbMEfQiI4eJQ_hrACj9f9hhks5qLwNZgaJpZM4I1nWL>.


=====================================================================

     Please note that this e-mail and any files transmitted from
     Memorial Sloan Kettering Cancer Center may be privileged, confidential,
     and protected from disclosure under applicable law. If the reader of
     this message is not the intended recipient, or an employee or agent
     responsible for delivering this message to the intended recipient,
     you are hereby notified that any reading, dissemination, distribution,
     copying, or other use of this communication or any of its attachments
     is strictly prohibited.  If you have received this communication in
     error, please notify the sender immediately by replying to this message
     and deleting this message, any attachments, and all copies and backups
     from your computer.

**Comment by brianjohnhaas** [comment]
You might need to directly install Berkeley db.  Most systems I've worked with already have had it installed.  If you need help locating it let me know.  

Best

-Brian
(by iPhone)
